/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizapplication;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.*;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SeeMonster
 */
public class Exam extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    Statement s;
    ResultSet res;

    /**
     * Creates new form Question
     */
    public Exam() {
        initComponents();
        btnSave.setEnabled(false);
        btnFinish.setEnabled(false);

        loadCategories();
        

        comboExamCat.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {

                //get available test numbers
                String q = "select DISTINCT test_no from questions where q_cat=?";

                try {

                    con = DBConnection.connecttoDB();
                    ps = con.prepareStatement(q);
                    ps.setString(1, comboExamCat.getSelectedItem().toString());
                    res = ps.executeQuery();

                    if (!res.next()) {
                        JOptionPane.showMessageDialog(null, "No Test Avalilable in this Category");
                        
                        btnStart.setEnabled(false);
                        btnFinish.setEnabled(false);
                        btnSave.setEnabled(false);
                    } else {
                        res.beforeFirst();
                        comboTestNo.removeAllItems();
                        while (res.next()) {

                            String s = res.getString(1);
                            //add results to combo
                            comboTestNo.addItem("Test " + s);
                        }

                        
                         btnStart.setEnabled(true);
                        btnFinish.setEnabled(true);
                        btnSave.setEnabled(true);
                        
                    }

                    ps.close();
                    res.close();
                    con.close();

                } catch (SQLException ex) {
                    ex.printStackTrace();
                }

            }
        });

    }

    public void loadCategories() {

        try {
            con = DBConnection.connecttoDB();
            ps = con.prepareStatement("select * from cat");
            res = ps.executeQuery();

            if (!res.next()) {

                JOptionPane.showMessageDialog(null, "No record found ...");

            } else {
                res.beforeFirst();

                comboExamCat.removeAllItems();
                //add empty item
                comboExamCat.addItem("None");
                
                while (res.next()) {

                    comboExamCat.addItem(res.getString(2));
                }

            }

            ps.close();
            res.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblqno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taqtext = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        textA = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        textB = new javax.swing.JTextField();
        textC = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        textD = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        lbltotalnum = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();
        lblAns = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboExamCat = new javax.swing.JComboBox<>();
        lblCorrectAns = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboTestNo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        textStuID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        textStuName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Exam");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Question No:");

        lblqno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblqno.setForeground(new java.awt.Color(51, 102, 255));
        lblqno.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Question:");

        taqtext.setColumns(20);
        taqtext.setRows(5);
        taqtext.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taqtext);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("A)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("B)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("C)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("D)");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnNext.setText("Next>");
        btnNext.setEnabled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnStart.setText("Start Exam");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        lbltotalnum.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbltotalnum.setForeground(new java.awt.Color(51, 102, 255));

        btnPrev.setText("<Prev");
        btnPrev.setEnabled(false);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnFinish.setText("Finish Exam");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        lblAns.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAns.setForeground(new java.awt.Color(255, 102, 51));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Exam Category:");

        comboExamCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Mathematics", "Programming", "Animals" }));
        comboExamCat.setSelectedIndex(-1);

        lblCorrectAns.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorrectAns.setForeground(new java.awt.Color(0, 204, 51));
        lblCorrectAns.setText("ada");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Test No:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Student ID:");

        textStuID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Student Name:");

        textStuName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(lbltotalnum, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblAns, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCorrectAns, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btnStart)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnFinish)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPrev)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext)
                                .addGap(31, 31, 31)
                                .addComponent(btnSave))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textD, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboExamCat, 0, 224, Short.MAX_VALUE)
                            .addComponent(lblqno)
                            .addComponent(comboTestNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textStuID)
                            .addComponent(textStuName))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboExamCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboTestNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textStuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textStuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblqno)
                    .addComponent(lbltotalnum)
                    .addComponent(lblAns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnStart)
                    .addComponent(btnPrev)
                    .addComponent(btnSave)
                    .addComponent(btnFinish))
                .addGap(18, 18, 18)
                .addComponent(lblCorrectAns)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Please press \"Start\" to start quiz,press \"prev/next\" to see other questions,press \"Save\" to give your answer.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("You can change your answer any time you want by clicking \"A\",\"B\",\"C\",\"D\" buttons and then clicking \"Save\" button.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String cur_test_no;

    public void getNextQuestion(int qno, String action) {

        String cat = comboExamCat.getSelectedItem().toString();
        try {
            con = DBConnection.connecttoDB();

            //total num of questions
            s = con.createStatement();

            cur_test_no = comboTestNo.getSelectedItem().toString().split(" ")[1];
            res = s.executeQuery("select max(q_no) from questions WHERE q_cat='" + cat + "' AND test_no='" + cur_test_no + "'");

            res.next();
            int totalnum = res.getInt(1);

            s.close();
            res.close();

            //return next question
            s = con.createStatement();
            res = s.executeQuery("select * from questions WHERE q_cat='" + cat + "'AND test_no='" + cur_test_no + "' AND q_no=" + qno);

            if (res.next()) {

                String q_no = res.getString(2).toString();
                String q_text = res.getString(3).toString();
                String optA = res.getString(4).toString();
                String optB = res.getString(5).toString();
                String optC = res.getString(6).toString();
                String optD = res.getString(7).toString();
                String ans = res.getString(8).toString();

                lblqno.setText(q_no);
                lbltotalnum.setText(String.valueOf("Total :" + totalnum));
                taqtext.setText(q_text);
                textA.setText(optA);
                textB.setText(optB);
                textC.setText(optC);
                textD.setText(optD);

                s.close();
                res.close();
                con.close();

                btnNext.setEnabled(true);
                btnPrev.setEnabled(true);
            } else {
                if (action.equals("next")) {
                    btnNext.setEnabled(false);
                }

                if (action.equals("prev")) {
                    btnPrev.setEnabled(false);
                }
            }

        } catch (SQLException ex) {

            Logger.getLogger(Exam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    boolean validStudent = false;
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

        //check student ID
        con = DBConnection.connecttoDB();
        try {
            ps = con.prepareStatement("select * from students WHERE id=? AND fullname=?");
            ps.setString(1, textStuID.getText().toString());
            ps.setString(2, textStuName.getText().toString());
            res = ps.executeQuery();

            if (res.next()) {
                validStudent = true;
            }

        } catch (SQLException ex) {
            Logger.getLogger(Exam.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (validStudent == true) {
            //start Exam
            textStuID.setEnabled(false);
            textStuName.setEnabled(false);
            comboExamCat.setEnabled(false);
            comboTestNo.setEnabled(false);
            btnStart.setEnabled(false);
            btnNext.setEnabled(true);
            btnPrev.setEnabled(true);
             btnSave.setEnabled(true);
             btnFinish.setEnabled(true);
            int qno = Integer.parseInt(lblqno.getText().toString()) + 1;
            getNextQuestion(qno, "");
        } else {
            JOptionPane.showMessageDialog(null, "Not a valid student ID OR name");
            textStuID.setText("");
            textStuName.setText("");
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        int qno = Integer.parseInt(lblqno.getText().toString()) + 1;
        getNextQuestion(qno, "next");

        int index = Integer.parseInt(lblqno.getText().toString());
        if (answers.get(String.valueOf(index - 1)) == null) {
            lblAns.setText("Your Answer :" + "-");
        } else {
            lblAns.setText(answers.get(String.valueOf(index)));
        }

        lblCorrectAns.setText("");
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        int qno = Integer.parseInt(lblqno.getText().toString()) - 1;
        getNextQuestion(qno, "prev");

        int index = Integer.parseInt(lblqno.getText().toString());
        if (answers.get(String.valueOf(index)) == null) {
            lblAns.setText("Your Answer :" + "-");
        } else {
            lblAns.setText(answers.get(String.valueOf(index)));
        }

        lblCorrectAns.setText("");
    }//GEN-LAST:event_btnPrevActionPerformed

    int score = 0;
    String wrongs = "Wrong answered questions : ";
    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed

        //delete given answers
        con = DBConnection.connecttoDB();
        Statement s;
        try {
            s = con.createStatement();
            s.executeUpdate("update questions SET q_given_ans=NULL WHERE q_cat='" + comboExamCat.getSelectedItem().toString() + "' AND test_no='" + cur_test_no + "'");

            s.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(Exam.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            //Finish Exam

            con = DBConnection.connecttoDB();
            s = con.createStatement();
            int i = 0;
            while (i < answers.size()) {

                Object key = answers.keySet().toArray()[i];
                String value = answers.get(key);
                String k = String.valueOf(key);
                String val = value.split(":")[1];

                System.out.println("\nval : " + val);
                s.executeUpdate("update questions SET q_given_ans='" + val + "' WHERE q_cat='" + comboExamCat.getSelectedItem().toString() + "' AND test_no='" + cur_test_no + "' AND q_no='" + k + "'");

                i++;
            }

            s.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(Exam.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            con = DBConnection.connecttoDB();
            //return marks
            s = con.createStatement();
            res = s.executeQuery("select q_no,q_cor_ans,q_given_ans from questions WHERE q_cat='" + comboExamCat.getSelectedItem().toString() + "' AND test_no='" + cur_test_no + "'");

            while (res.next()) {

                String given = res.getString("q_given_ans");
                String correct = res.getString("q_cor_ans");
                String qnumber = res.getString("q_no");

                try {

                    if (given.equals(correct)) {
                        score++;
                    } else {
                        wrongs += qnumber + "(" + correct + ") , ";
                    }

                } catch (Exception ex) {

                }
                System.out.println("given from db" + given);
            }

            lblCorrectAns.setText(String.valueOf(score));
            System.out.println("wrongs :" + wrongs);

            Result r = new Result(
                    comboExamCat.getSelectedItem().toString(),
                    comboTestNo.getSelectedItem().toString(),
                    textStuID.getText().toString(),
                    textStuName.getText().toString(),
                    wrongs,
                    score);

            r.setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(Exam.class.getName()).log(Level.SEVERE, null, ex);
        }

        comboExamCat.setEnabled(true);
        comboTestNo.setEnabled(true);
        textStuID.setEnabled(true);
        textStuName.setEnabled(true);


    }//GEN-LAST:event_btnFinishActionPerformed

    //store answers
    HashMap<String, String> answers = new HashMap<String, String>();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        lblAns.setText("Your Answer :" + "A");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        lblAns.setText("Your Answer :" + "B");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        lblAns.setText("Your Answer :" + "C");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        lblAns.setText("Your Answer :" + "D");

    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        lblCorrectAns.setText("Saved");

        int index = Integer.parseInt(lblqno.getText().toString());
        answers.put(String.valueOf(index), lblAns.getText());

        Object key = answers.keySet().toArray()[index - 1];
        String value = answers.get(key);

        System.out.println((String) key + " : " + value);
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnStart;
    private javax.swing.JComboBox<String> comboExamCat;
    private javax.swing.JComboBox<String> comboTestNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAns;
    private javax.swing.JLabel lblCorrectAns;
    private javax.swing.JLabel lblqno;
    private javax.swing.JLabel lbltotalnum;
    private javax.swing.JTextArea taqtext;
    private javax.swing.JTextField textA;
    private javax.swing.JTextField textB;
    private javax.swing.JTextField textC;
    private javax.swing.JTextField textD;
    private javax.swing.JTextField textStuID;
    private javax.swing.JTextField textStuName;
    // End of variables declaration//GEN-END:variables
}
